"""Build the static data file for the browser demo (demo/data.json).

The demo is a replay: every eval query with its top 10 from the zero-shot baseline
(BGE-M3 over English fields) and from the final system (fine-tuned BGE-M3 over
Turkish fields + teacher description), relevance marked from eval/qrels.jsonl.
Each listed perfume carries a Turkish description generated by the distilled
student (Qwen3-0.6B + LoRA, Q4_K_M GGUF) through llama-server; outputs are cached
in data/student.jsonl so reruns only generate what is missing.

Run: uv run python demo/build.py
"""
import json
import os
import subprocess
import sys
import time
import urllib.request
from concurrent.futures import ThreadPoolExecutor

from transformers import AutoTokenizer

sys.path.insert(0, "distill")
sys.path.insert(0, "eval")
from generate import GENDER_TR, TR, parse  # noqa: E402
from label import corpus  # noqa: E402
from sft import BASE, chat, split  # noqa: E402

RUNS = {"baseline": "runs/dense-bge-m3.jsonl", "final": "runs/dense-bge-m3-koku-desc.jsonl"}
CACHE = "data/student.jsonl"
GGUF = "models/gguf/koku-0.6b-q4_k_m.gguf"
PORT = 8092


def load_jsonl(path: str) -> list[dict]:
    with open(path, encoding="utf-8") as f:
        return [json.loads(l) for l in f if l.strip()]


def complete(prompt: str) -> str:
    body = {"prompt": prompt, "n_predict": 320, "temperature": 0, "cache_prompt": True}
    req = urllib.request.Request(f"http://127.0.0.1:{PORT}/completion", json.dumps(body).encode(), {"Content-Type": "application/json"})
    with urllib.request.urlopen(req, timeout=300) as r:
        return json.load(r)["content"]


def generate(ids: list[int], by: dict) -> None:
    done = {r["id"] for r in load_jsonl(CACHE)} if os.path.exists(CACHE) else set()
    todo = [i for i in ids if i not in done]
    print(f"student descriptions: {len(done)} cached, {len(todo)} to generate")
    if not todo:
        return
    tok = AutoTokenizer.from_pretrained(BASE)
    srv = subprocess.Popen(["tools/llama.cpp/llama-server.exe", "-m", GGUF, "-ngl", "99", "-c", "8192", "-np", "4",
                            "--port", str(PORT), "--host", "127.0.0.1"], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    try:
        for _ in range(120):
            try:
                urllib.request.urlopen(f"http://127.0.0.1:{PORT}/health", timeout=2)
                break
            except OSError:
                time.sleep(1)
        with open(CACHE, "a", encoding="utf-8") as f, ThreadPoolExecutor(4) as pool:
            for n, (i, text) in enumerate(zip(todo, pool.map(lambda i: complete(chat(tok, by[i])), todo)), 1):
                d = parse(text)
                f.write(json.dumps({"id": i, "description": d["description"] if d else None}, ensure_ascii=False) + "\n")
                if n % 200 == 0:
                    print(f"{n}/{len(todo)}", flush=True)
    finally:
        srv.terminate()
        srv.wait()


if __name__ == "__main__":
    by = {p["id"]: p for p in corpus()}
    runs = {k: {r["id"]: r["ranking"][:10] for r in load_jsonl(v)} for k, v in RUNS.items()}
    qrels = {r["id"]: set(r["relevant"]) for r in load_jsonl("eval/qrels.jsonl")}
    queries = load_jsonl("eval/queries.jsonl")
    ids = sorted({i for r in runs.values() for top in r.values() for i in top})
    generate(ids, by)

    student = {r["id"]: r["description"] for r in load_jsonl(CACHE)}
    _, held, _ = split()
    held_ids = {r["id"] for r in held}
    tr_a = TR["accords"]
    perfumes = {i: {"n": by[i]["name"], "b": by[i]["brand"], "g": GENDER_TR.get(by[i]["gender"], by[i]["gender"]),
                    "a": [tr_a.get(a, a) for a in by[i]["accords"][:3]], "d": student.get(i), "h": i in held_ids}
                for i in ids}
    out = {"queries": [{"id": q["id"], "t": q["type"], "q": q["query"],
                        **{k: [[i, int(i in qrels[q["id"]])] for i in runs[k][q["id"]]] for k in RUNS}} for q in queries],
           "perfumes": perfumes}
    with open("demo/data.json", "w", encoding="utf-8") as f:
        json.dump(out, f, ensure_ascii=False, separators=(",", ":"))
    missing = sum(1 for p in perfumes.values() if not p["d"])
    print(f"wrote demo/data.json: {len(out['queries'])} queries, {len(perfumes)} perfumes, "
          f"{missing} without a valid student description, {os.path.getsize('demo/data.json') // 1024} KB")
